include(
    ":app",
    ":base",
    ":data",
    ":rest",
    ":rest-implementation",
    ":di",
    ":scheduler",
    ":scheduler-implementation",
    ":theme",
    ":recyclerview",
    ":mvi",
    ":mvi-lifecycle",
    ":imageloader",
    ":featureweather"
)
