package weather.feature.weather

object IconCodeMapper {

    fun code(id: Long): Icon {
        return when (id) {
            200L -> Icon("thunderstorm", "day-", "night-alt-")
            201L -> Icon("thunderstorm", "day-", "night-alt-")
            202L -> Icon("thunderstorm", "day-", "night-alt-")
            210L -> Icon("lightning", "day-", "night-alt-")
            211L -> Icon("lightning", "day-", "night-alt-")
            212L -> Icon("lightning", "day-", "night-alt-")
            221L -> Icon("lightning", "day-", "night-alt-")
            230L -> Icon("thunderstorm", "day-", "night-alt-")
            231L -> Icon("thunderstorm", "day-", "night-alt-")
            232L -> Icon("thunderstorm", "day-", "night-alt-")
            300L -> Icon("sprinkle", "day-", "night-alt-")
            301L -> Icon("sprinkle", "day-", "night-alt-")
            302L -> Icon("rain", "day-", "night-alt-")
            310L -> Icon("rain", "day-", "night-alt-")
            311L -> Icon("rain", "day-", "night-alt-")
            312L -> Icon("rain", "day-", "night-alt-")
            313L -> Icon("rain", "day-", "night-alt-")
            314L -> Icon("rain", "day-", "night-alt-")
            321L -> Icon("sprinkle", "day-", "night-alt-")
            500L -> Icon("sprinkle", "day-", "night-alt-")
            501L -> Icon("rain", "day-", "night-alt-")
            502L -> Icon("rain", "day-", "night-alt-")
            503L -> Icon("rain", "day-", "night-alt-")
            504L -> Icon("rain", "day-", "night-alt-")
            511L -> Icon("rain-mix", "day-", "night-alt-")
            520L -> Icon("showers", "day-", "night-alt-")
            521L -> Icon("showers", "day-", "night-alt-")
            522L -> Icon("showers", "day-", "night-alt-")
            531L -> Icon("storm-showers", "day-", "night-alt-")
            600L -> Icon("snow", "day-", "night-alt-")
            601L -> Icon("sleet", "day-", "night-alt-")
            602L -> Icon("snow", "day-", "night-alt-")
            611L -> Icon("rain-mix", "day-", "night-alt-")
            612L -> Icon("rain-mix", "day-", "night-alt-")
            615L -> Icon("rain-mix", "day-", "night-alt-")
            616L -> Icon("rain-mix", "day-", "night-alt-")
            620L -> Icon("rain-mix", "day-", "night-alt-")
            621L -> Icon("snow", "day-", "night-alt-")
            622L -> Icon("snow", "day-", "night-alt-")
            701L -> Icon("showers", "day-", "night-alt-")
            711L -> Icon("smoke")
            721L -> Icon("day-haze")
            731L -> Icon("dust")
            741L -> Icon("fog", "day-", "night-")
            761L -> Icon("dust", "", "")
            762L -> Icon("dust", "", "")
            781L -> Icon("tornado", "", "")
            800L -> Icon("", "day-sunny", "night-clear")
            801L -> Icon("cloudy-gusts", "day-", "night-alt-")
            802L -> Icon("cloudy-gusts", "day-", "night-alt-")
            803L -> Icon("cloudy-gusts", "day-", "night-alt-")
            804L -> Icon("cloudy", "day-", "night-alt-")
            900L -> Icon("tornado", "", "")
            902L -> Icon("hurricane", "", "")
            903L -> Icon("snowflake-cold", "", "")
            904L -> Icon("hot", "", "")
            906L -> Icon("hail", "day-", "night-alt-")
            957L -> Icon("strong-wind", "", "")
            else -> Icon("alien", "", "")
        }
    }
}
